version: "3"
services:
 backend-example-docker:
  build: ./backend-example-docker
  image: joukorintamaki/backend-example-docker
  container_name: backend-example-docker
  environment:
   - REDIS=redis
   - DB_USERNAME=postgres@postgres-devopswithdocker2019.postgres.database.azure.com
   - DB_PASSWORD=z4R25sru
   - DB_NAME=postgres
   - DB_HOST=postgres-devopswithdocker2019.postgres.database.azure.com
  ports:
   - 8000:8000
 frontend-example-docker:
  build: ./frontend-example-docker
  image: joukorintamaki/frontend-example-docker
  container_name: frontend-example-docker
  ports:
   - 5000:5000
 redis:
  container_name: redis
  image: redis:alpine
  ports:
    - 6379
 nginxservice:  
  build: ./nginxservice
  image: joukorintamaki/nginxservice  
  container_name: nginxservice
  ports:
   - 80:80
  environment:
   - NGINX_PORT=80
