apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-example-docker
  name: frontend-example-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-example-docker
  template:
    metadata:
      labels:
        app: frontend-example-docker
    spec:
      containers:
        - image: joukorintamaki/frontend-example-docker
          name: frontend-example-docker
          ports:
            - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: aks-nodepool1-16828242-vmss000000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-example-docker
  name: backend-example-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-example-docker
  template:
    metadata:
      labels:
        app: backend-example-docker
    spec:
      containers:
        - image: joukorintamaki/backend-example-docker
          name: backend-example-docker
          ports:
            - containerPort: 8000
      nodeSelector:
        kubernetes.io/hostname: aks-nodepool1-16828242-vmss000001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-example-docker
  name: frontend-example-docker
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: frontend-example-docker
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-example-docker
  name: backend-example-docker
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: backend-example-docker
  type: LoadBalancer
