version: "3"
services:
 backend-example-docker:
  build: ./backend-example-docker
  image: joukorintamaki/backend-example-docker
  container_name: backend-example-docker
  environment:
   - REDIS=redis
   - DB_USERNAME=postgres
   - DB_PASSWORD=salasana
   - DB_HOST=postgres
  ports:
   - 8000:8000
 frontend-example-docker:
  build: ./frontend-example-docker
  image: joukorintamaki/frontend-example-docker
  container_name: frontend-example-docker
  ports:
   - 5000:5000
 redis:
  container_name: redis
  image: redis:alpine
  ports:
    - 6379
 postgres:
  container_name: postgres
  image: postgres:alpine  
  environment:
   - POSTGRES_USERNAME=postgres
   - POSTGRES_PASSWORD=salasana
  volumes:
   - database:/var/lib/postgresql/data
 nginxservice:  
  build: ./nginxservice
  image: joukorintamaki/nginxservice  
  container_name: nginxservice
  ports:
   - 80:80
  environment:
   - NGINX_PORT=80
volumes:
 database:
