version: "3.3"
services:
 backend-example-docker:
  build: ./backend-example-docker
  container_name: backend-example-docker
  ports:
   - 8000:8000
  image: backend-example-docker

 frontend-example-docker:
  build: ./frontend-example-docker
  container_name: frontend-example-docker
  ports:
   - 5000:5000
  image: frontend-example-docker
