version: "3.7"
services:
 backend-example-docker:
  build: ./backend-example-docker
  container_name: backend-example-docker
  environment:
   - REDIS=redis
   - DB_USERNAME=postgres
   - DB_PASSWORD=salasana
   - DB_HOST=postgres
  ports:
   - 8000:8000
  image: backend-example-docker
 frontend-example-docker:
  build: ./frontend-example-docker
  container_name: frontend-example-docker
  ports:
   - 5000:5000
  image: frontend-example-docker
 redis:
  container_name: redis
  image: redis
  ports:
    - 6379
 postgres:
  container_name: postgres
  image: postgres
  restart: unless-stopped
  environment:
   - POSTGRES_USERNAME=postgres
   - POSTGRES_PASSWORD=salasana
 nginx:
  container_name: nginx
  image: nginx
  ports:
   - 80:80
  environment:
   - NGINX_PORT=80
  volumes:
   - /c/Temp/nginx.conf:/etc/nginx/nginx.conf
